In [ ]:
#groupby on multiple cols
#size
#get_group

In [4]:
import numpy as np
import pandas as pd
imdb_df=pd.read_csv(r'C:\Users\HP\Desktop\all folder\pandas\imdb-top-1000.csv')
genres=imdb_df.groupby('Genre')

In [7]:
#groupby on multiple cols
duo=imdb_df.groupby(['Director','Star1'])
duo
duo.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [8]:
#get_group -- pass tuple
duo.get_group(('Aamir Khan','Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [11]:
#que- find the most earning actor - director combo
duo['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [13]:
#find the best(in terms of metascore(avg)) actor- genre combo
imdb_df.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False)

                Star1    Genre  Metascore
230    Ellar Coltrane    Drama      100.0
329   Humphrey Bogart    Drama      100.0
360     James Stewart  Mystery      100.0
77        Bertil Guve    Drama      100.0
590      Orson Welles    Drama      100.0
..                ...      ...        ...
807    William Holden    Drama        NaN
812           Won Bin   Action        NaN
815              Yash   Action        NaN
826    Çetin Tekindor    Drama        NaN
828  Ömer Faruk Sorak   Comedy        NaN

[829 rows x 3 columns]

In [15]:
#agg on multiple col
duo.agg(['min','max'])

                                                  Series_Title  \
                                                           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab
Abhishek Kapoor     Amit Sadh                      Kai po che!
...                                                        ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara
                    Vijay Varma                      Gully Boy
Çagan Irmak         Çetin Tekindor              Babam ve Oglum
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.

                                                               Released_Year  \
                                                           max           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par          2007
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7          2020
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle          2013
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab          2016
Abhishek Kapoor     Amit Sadh                      Kai po che!          2013
...                                                        ...           ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid          2013
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara          2011
                    Vijay Varma                      Gully Boy          2019
Çagan Irmak         Çetin Tekindor              Babam ve Oglum          2005
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.          2004

                                         Runtime           Genre             \
                                     max     min  max        min        max
Director            Star1
Aamir Khan          Amole Gupte     2007     165  165      Drama      Drama
Aaron Sorkin        Eddie Redmayne  2020     129  129      Drama      Drama
Abdellatif Kechiche Léa Seydoux     2013     180  180      Drama      Drama
Abhishek Chaubey    Shahid Kapoor   2016     148  148     Action     Action
Abhishek Kapoor     Amit Sadh       2013     130  130      Drama      Drama
...                                  ...     ...  ...        ...        ...
Zaza Urushadze      Lembit Ulfsak   2013      87   87      Drama      Drama
Zoya Akhtar         Hrithik Roshan  2011     155  155     Comedy     Comedy
                    Vijay Varma     2019     154  154      Drama      Drama
Çagan Irmak         Çetin Tekindor  2005     112  112      Drama      Drama
Ömer Faruk Sorak    Cem Yilmaz      2004     127  127  Adventure  Adventure

                                   IMDB_Rating      No_of_Votes          \
                                           min  max         min     max
Director            Star1
Aamir Khan          Amole Gupte            8.4  8.4      168895  168895
Aaron Sorkin        Eddie Redmayne         7.8  7.8       89896   89896
Abdellatif Kechiche Léa Seydoux            7.7  7.7      138741  138741
Abhishek Chaubey    Shahid Kapoor          7.8  7.8       27175   27175
Abhishek Kapoor     Amit Sadh              7.7  7.7       32628   32628
...                                        ...  ...         ...     ...
Zaza Urushadze      Lembit Ulfsak          8.2  8.2       40382   40382
Zoya Akhtar         Hrithik Roshan         8.1  8.1       67927   67927
                    Vijay Varma            8.0  8.0       31886   31886
Çagan Irmak         Çetin Tekindor         8.3  8.3       78925   78925
Ömer Faruk Sorak    Cem Yilmaz             8.0  8.0       56960   56960

                                          Gross              Metascore
                                            min          max       min   max
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0       NaN   NaN
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0      77.0  77.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0      89.0  89.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0       NaN   NaN
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0      40.0  40.0
...                                         ...          ...       ...   ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0      73.0  73.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0       NaN   NaN
                    Vijay Varma       5566534.0    5566534.0      65.0  65.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0       NaN   NaN
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0       NaN   NaN

[898 rows x 16 columns]